export enum UserPermissionType {
  USER_RIGHTS = "USER_RIGHTS",
  PRODUCT_RIGHTS = "PRODUCT_RIGHTS",
  PURCHASE_ORDER_RIGHTS = "PURCHASE_ORDER_RIGHTS",
  CREATE_PURCHASE_ORDER = "CREATE_PURCHASE_ORDER",
  VIEW_PURCHASE_ORDER = "VIEW_PURCHASE_ORDER",
  UPDATE_PURCHASE_ORDER = "UPDATE_PURCHASE_ORDER",
  CANCEL_PURCHASE_ORDER = "CANCEL_PURCHASE_ORDER",
  SETUP_RIGHTS = "SETUP_RIGHTS",
  MANAGEMENT_RIGHTS = "MANAGEMENT_RIGHTS",
  REPORTING_RIGHTS = "REPORTING_RIGHTS",
  MARGIN_RIGHTS = "MARGIN_RIGHTS",
  TILL_RIGHTS = "TILL_RIGHTS",
  WEB_INTEGRATION_RIGHTS = "WEB_INTEGRATION_RIGHTS",
  APPS_RIGHTS = "APPS_RIGHTS",
}

export enum Status {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
}

export interface User {
  id: string;
  username?: string;
  password: string;
  email?: string;
  status: Status;
  permissions: UserPermissionType[];
}
