export const SidebarData1 = [
  {
    title: 'Main Menu',
    hasSubRoute: true,
    icon: 'layout-grid',
    showSubRoute: false,
    route: "/index",
    subRoutes: [
      {
        title: 'Dashboard',
        hasSubRoute: true,
        showSubRoute: true,
        subRoutes: [
          {
            title: 'Admin Dashboard',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/index",
            subRoutes: [],
          },
          {
            title: 'Sales Dashboard',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/sales-dashboard",
            subRoutes: [],
          },
        ],
      },
      {
        title: 'Layouts',
        hasSubRoute: true,
        icon: 'layout-sidebar-right-collapse',
        showSubRoute: false,
        subRoutes: [
          {
            title: 'Horizontal',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-horizontal",
            subRoutes: [],
          },
          {
            title: 'Detached',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-detached",
            subRoutes: [],
          },
          {
            title: 'Modern',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-modern",
            subRoutes: [],
          },
          {
            title: 'Two Column',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-two-column",
            subRoutes: [],
          },
          {
            title: 'Hovered',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-hovered",
            subRoutes: [],
          },
          {
            title: 'Boxed',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-boxed",
            subRoutes: [],
          },
          {
            title: 'RTL',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-rtl",
            subRoutes: [],
          },
          {
            title: 'Dark',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/layout-dark",
            subRoutes: [],
          },
        ],
      },
    ],
  },
  {
    title: 'Inventory',
    hasSubRoute: true,
    icon: 'brand-unity',
    showSubRoute: false,
    activeRoute: 'product',
    subRoutes: [
      {
        title: 'Product-view',
        hasSubRoute: false,
        showSubRoute: true,
        route: "/product-view",
        subRoutes: [],
      },
      {
        title: 'Products',
        hasSubRoute: false,
        showSubRoute: true,
        route: "/product-list",
        subRoutes: [],
      },
      {
        title: 'Create Product',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/add-product",
        subRoutes: [],
      },
      {
        title: 'Expired Products',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/expired-products",
        subRoutes: [],
      },
      {
        title: 'Low Stocks',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/low-stocks",
        subRoutes: [],
      },
      {
        title: 'Category',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/category-list",
        subRoutes: [],
      },
      {
        title: 'Sub Category',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/sub-categories",
        subRoutes: [],
      },
      {
        title: 'Brands',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/brand-list",
        subRoutes: [],
      },
      {
        title: 'Units',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/units",
        subRoutes: [],
      },
      {
        title: 'Variant Attributes',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/variant-attributes",
        subRoutes: [],
      },
      {
        title: 'Warranties',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/warranty",
        subRoutes: [],
      },
      {
        title: 'Print Barcode',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/barcode",
        subRoutes: [],
      },
      {
        title: 'Print QR Code',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/qrcode",
        subRoutes: [],
      },
    ],
  },
  {
    title: 'Sales & Purchase',
    hasSubRoute: true,
    icon: 'layout-grid',
    showSubRoute: false,
    activeRoute: 'users',
    subRoutes: [
      {
        title: 'Stock',
        hasSubRoute: true,
        showSubRoute: false,
        subRoutes: [
          {
            title: 'Manage Stock',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/manage-stocks",
            subRoutes: [],
          },
          {
            title: 'Stock Movements',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-movements",
            subRoutes: [],
          },
          {
            title: 'Stock Adjustment',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-adjustment",
            subRoutes: [],
          },
          {
            title: 'Stock Transfer',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-transfer",
            subRoutes: [],
          },
          {
            title: 'Stock Audit History',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-audit-history",
            subRoutes: [],
          },
          {
            title: 'Stock Level',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-level",
            subRoutes: [],
          },
          {
            title: 'Non-Selling Stocks',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/non-selling-stocks",
            subRoutes: [],
          },
          {
            title: 'Stock Warnings',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/stock-warnings",
            subRoutes: [],
          },
        ],
      },
      {
        title: 'Sales',
        hasSubRoute: true,
        showSubRoute: false,
        route: "/sales-list",
        subRoutes: [
          {
            title: 'Sales',
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                title: 'Online Orders',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/online-orders",
                subRoutes: [],
              },
              {
                title: 'POS Orders',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/pos-orders",
                subRoutes: [],
              },
            ],
          },
        ],
      },
      {
        title: 'Promo',
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: 'promo',
        subRoutes: [
          {
            title: 'Coupons',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/coupons",
            subRoutes: [],
          },
          {
            title: 'Gift Cards',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/gift-cards",
            subRoutes: [],
          },
          {
            title: 'Discount',
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                title: 'Discount Plan',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/discount-plan",
                subRoutes: [],
              },
              {
                title: 'Discount',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/discount",
                subRoutes: [],
              },
            ],
          },
        ],
      },
      {
        title: 'Purchases',
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: 'users',
        subRoutes: [
          {
            title: 'Purchases',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-list",
            subRoutes: [],
          },
          {
            title: 'Purchase Order',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-order-report",
            subRoutes: [],
          },
          {
            title: 'Purchase Return',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/purchase-returns",
            subRoutes: [],
          },
          {
            title: 'Expenses',
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                title: 'Expenses',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/expense-list",
                subRoutes: [],
              },
              {
                title: 'Expense Category',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/expense-category",
                subRoutes: [],
              },
            ],
          },
        ],
      },
      {
        title: 'Expenses',
        hasSubRoute: true,
        showSubRoute: true,
        subRoutes: [
          {
            title: 'Expenses',
            route: "/expense-list",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
          {
            title: 'Expense Category',
            route: "/expense-category",
            hasSubRoute: false,
            showSubRoute: false,
            subRoutes: [],
          },
        ],
      },
      {
        title: 'Income',
        hasSubRoute: true,
        showSubRoute: false,
        route: "/purchase-returns",
        subRoutes: [
          {
            title: 'Income',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/income",
            subRoutes: [],
          },
          {
            title: 'Income Category',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/income-category",
            subRoutes: [],
          },
        ],
      },
      {
        title: 'Bank Accounts',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/account-list",
        subRoutes: [],
      },
      {
        title: 'Money Transfer',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/money-transfer",
        subRoutes: [],
      },
      {
        title: 'Balance Sheet',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/balance-sheet",
        subRoutes: [],
      },
      {
        title: 'Trial Balance',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/trial-balance",
        subRoutes: [],
      },
      {
        title: 'Cash Flow',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/cash-flow",
        subRoutes: [],
      },
      {
        title: 'Account Statement',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/account-statement",
        subRoutes: [],
      },
    ],
  },
  {
    title: 'Profile',
    hasSubRoute: true,
    icon: 'user-circle',
    showSubRoute: false,
    subRoutes: [
      // {
      //   tittle: 'Profile',
      //   route: "/profile",
      //   hasSubRoute: false,
      //   showSubRoute: false,
      // },
      // {
      //   tittle: 'Authentication',
      //   hasSubRoute: true,
      //   showSubRoute: false,
      //   //   route: routes.purchaseReport,
      //   subRoutes: [
      //     {
      //       tittle: 'Login',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/signin",
      //       subRoutes: [
      //         {
      //           tittle: 'Cover',
      //           route: "/signin",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Illustration',
      //           route: "/signin-2",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Basic',
      //           route: "/signin-3",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //       ],
      //     },
      //     {
      //       tittle: 'Register',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/register",
      //       subRoutes: [
      //         {
      //           tittle: 'Cover',
      //           route: "/signin",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Illustration',
      //           route: "/signin-2",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Basic',
      //           route: "/signin-3",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //       ],
      //     },
      //     {
      //       tittle: 'Forgot Password',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/forgot-password",
      //       subRoutes: [
      //         {
      //           tittle: 'Cover',
      //           route: "/forgot-password",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Illustration',
      //           route: "/signin-2",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Basic',
      //           route: "/signin-3",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //       ],
      //     },
      //     {
      //       tittle: 'Reset Password',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/reset-password",
      //       subRoutes: [
      //         {
      //           tittle: 'Cover',
      //           route: "/signin",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Illustration',
      //           route: "/signin-2",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Basic',
      //           route: "/signin-3",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //       ],
      //     },
      //     {
      //       tittle: 'Email Verification',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/email-verification",
      //       subRoutes: [
      //         {
      //           tittle: 'Cover',
      //           route: "/signin",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Illustration',
      //           route: "/signin-2",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Basic',
      //           route: "/signin-3",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //       ],
      //     },
      //     {
      //       tittle: '2 Step Verification',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/two-step-verification",
      //       subRoutes: [
      //         {
      //           tittle: 'Cover',
      //           route: "/signin",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Illustration',
      //           route: "/signin-2",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //         {
      //           tittle: 'Basic',
      //           route: "/signin-3",
      //           hasSubRoute: false,
      //           showSubRoute: false,
      //         },
      //       ],
      //     },
      //   ],
      // },
      // {
      //   tittle: 'Error',
      //   hasSubRoute: true,
      //   showSubRoute: false,
      //   //   route: routes.purchaseReport,
      //   subRoutes: [
      //     {
      //       tittle: '404 Error',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/error-404",
      //       subRoutes: [],
      //     },
      //     {
      //       tittle: '500 Error',
      //       hasSubRoute: true,
      //       showSubRoute: false,
      //       route: "/error-500",
      //       subRoutes: [],
      //     },

      //   ],
      // },
      // {
      //   tittle: 'Blank page',
      //   hasSubRoute: false,
      //   showSubRoute: false,
      //   route: "/blank-page",
      //   subRoutes: [],
      // },
      // {
      //   tittle: 'Pricing',
      //   hasSubRoute: false,
      //   showSubRoute: false,
      //   route: "/pricing",
      //   subRoutes: [],
      // },
      // {
      //   tittle: 'Comming Soon',
      //   hasSubRoute: false,
      //   showSubRoute: false,
      //   route: "/coming-soon",
      //   subRoutes: [],
      // },
      // {
      //   tittle: 'Under Maintenance',
      //   hasSubRoute: false,
      //   showSubRoute: false,
      //   route: "/under-maintenance",
      //   subRoutes: [],
      // },
      // {
      //   tittle: 'Content',
      //   hasSubRoute: true,
      //   showSubRoute: false,
      //   //   route: routes.purchaseReport,
      //   subRoutes: [
      //     {
      //       tittle: 'Pages',
      //       hasSubRoute: true,
      //       showSubRoute: true,
      //       // route:"/employees-grid",
      //       subRoutes: [
      //         {
      //           tittle: 'Pages',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/pages",
      //           subRoutes: [],
      //         }
      //       ],
      //     },
      //     {
      //       tittle: 'Blog',
      //       hasSubRoute: true,
      //       showSubRoute: true,
      //       subRoutes: [
      //         {
      //           tittle: 'All Blog',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/all-blog",
      //           subRoutes: [],
      //         },
      //         {
      //           tittle: 'Blog Tags',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/blog-tag",
      //           subRoutes: [],
      //         },
      //         {
      //           tittle: 'Categories',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/blog-categories",
      //           subRoutes: [],
      //         },
      //         {
      //           tittle: 'Blog Comments',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/blog-comments",
      //           subRoutes: [],
      //         },
      //       ],
      //     },
      //     {
      //       tittle: 'Location',
      //       hasSubRoute: true,
      //       showSubRoute: true,
      //       subRoutes: [
      //         {
      //           tittle: 'Countries',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/countries",
      //           subRoutes: [],
      //         },
      //         {
      //           tittle: 'States',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/states",
      //           subRoutes: [],
      //         },
      //         {
      //           tittle: 'Cities',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/cities",
      //           subRoutes: [],
      //         },
      //         {
      //           tittle: 'Testimonials',
      //           hasSubRoute: true,
      //           showSubRoute: true,
      //           route: "/testimonials",
      //           subRoutes: [],
      //         },
      //       ],
      //     },
      //     {
      //       tittle: 'FAQ',
      //       hasSubRoute: false,
      //       showSubRoute: false,
      //       route: "/faq",
      //       subRoutes: [],
      //     },

      //   ],
      // },
      {
        title: 'Employees',
        hasSubRoute: true,
        showSubRoute: false,
        //   route: routes.purchaseReport,
        subRoutes: [
          {
            title: 'Employees',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/employees-grid",
            subRoutes: [],
          },
          {
            title: 'Designations',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/designation",
            subRoutes: [],
          },
          {
            title: 'Departments',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/department-grid",
            subRoutes: [],
          },
          {
            title: 'Shifts',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/shift",
            subRoutes: [],
          }

        ],
      },
      {
        title: 'Attendance',
        hasSubRoute: true,
        showSubRoute: false,
        //   route: routes.purchaseReport,
        subRoutes: [
          {
            title: 'Employee Attendance',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/attendance-employee",
            subRoutes: [],
          },
          {
            title: 'Admin Attendance',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/attendance-admin",
            subRoutes: [],
          },
        ],
      },
      {
        title: 'Leave & Holidays',
        hasSubRoute: true,
        showSubRoute: false,
        //   route: routes.purchaseReport,
        subRoutes: [
          {
            title: 'Admin Leaves',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/leaves-admin",
            subRoutes: [],
          },
          {
            title: 'Employee Leaves',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/leaves-employee",
            subRoutes: [],
          },
          {
            title: 'Leave Types',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/leave-types",
            subRoutes: [],
          },
          {
            title: 'Holidays',
            hasSubRoute: true,
            showSubRoute: false,
            route: "/holidays",
            subRoutes: [],
          },
          {
            title: 'Payroll',
            hasSubRoute: true,
            showSubRoute: true,
            route: "/employee-salary",
            subRoutes: [
              {
                title: 'Employee Salary',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/employee-salary",
                subRoutes: [],
              },
              {
                title: 'Payslip',
                hasSubRoute: false,
                showSubRoute: false,
                route: "/payslip",
                subRoutes: [],
              }
            ],
          },
        ],
      },
    ],
  },
  // {
  //   tittle: 'Reports',
  //   hasSubRoute: true,
  //   icon: 'chart-bar',
  //   showSubRoute: false,
  //   activeRoute: 'users',
  //   subRoutes: [
  //     {
  //       tittle: 'Sales Report',
  //       hasSubRoute: true,
  //       showSubRoute: true,
  //       subRoutes: [
  //         {
  //           tittle: 'Sales Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/sales-report",
  //         },
  //         {
  //           tittle: 'Best Seller',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/best-seller",
  //         },
  //       ],
  //     },
  //     {
  //       tittle: 'Purchase Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/purchase-report",
  //       subRoutes: [],
  //     },
  //     {
  //       tittle: 'Inventory Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/inventory-report",
  //       subRoutes: [
  //         {
  //           tittle: 'Inventory Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/inventory-report",
  //           subRoutes: []
  //         },
  //         {
  //           tittle: 'Stock History',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/stock-history",
  //           subRoutes: []
  //         },
  //         {
  //           tittle: 'Sold Stock',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/sold-stock",
  //           subRoutes: []
  //         },
  //       ],
  //     },
  //     {
  //       tittle: 'Invoice Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/invoice-report",
  //       subRoutes: [],
  //     },
  //     {
  //       tittle: 'Supplier Report',
  //       hasSubRoute: true,
  //       showSubRoute: true,
  //       subRoutes: [
  //         {
  //           tittle: 'Supplier Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/supplier-report",
  //           subRoutes: []
  //         },
  //         {
  //           tittle: 'Supplier Due Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/supplier-due-report",
  //           subRoutes: []
  //         },
  //       ],
  //     },

  //     {
  //       tittle: 'Customer Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       subRoutes: [
  //         {
  //           tittle: 'Customer Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/customer-report",
  //           subRoutes: []
  //         },
  //         {
  //           tittle: 'Customer Due Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/customer-due-report",
  //           subRoutes: []
  //         },
  //       ],
  //     },
  //     {
  //       tittle: 'Product Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       subRoutes: [
  //         {
  //           tittle: 'Product Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/product-report",
  //           subRoutes: []
  //         },
  //         {
  //           tittle: 'Product Expiry Report',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/product-expiry-report",
  //           subRoutes: []
  //         },
  //         {
  //           tittle: 'Product Quantity Alert',
  //           hasSubRoute: false,
  //           showSubRoute: false,
  //           route: "/product-quantity-alert",
  //           subRoutes: []
  //         },
  //       ],
  //     },
  //     {
  //       tittle: 'Expense Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/expense-report",
  //       subRoutes: [],
  //     },
  //     {
  //       tittle: 'Income Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/income-report",
  //       subRoutes: [],
  //     },
  //     {
  //       tittle: 'Tax Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/tax-report",
  //       subRoutes: [],
  //     },
  //     {
  //       tittle: 'Profit & Loss',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/profit-and-loss",
  //       subRoutes: [],
  //     },
  //     {
  //       tittle: 'Annual Report',
  //       hasSubRoute: false,
  //       showSubRoute: false,
  //       route: "/annual-report",
  //       subRoutes: [],
  //     },
  //   ],
  // },
  {
    title: 'Settings',
    hasSubRoute: true,
    icon: 'settings',
    showSubRoute: false,
    activeRoute: 'users',
    subRoutes: [
      {
        title: 'General Settings',
        hasSubRoute: true,
        showSubRoute: false,
        //   route: routes.users,
        subRoutes: [
          {
            title: 'Profile',
            route: "/profile",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Security',
            route: "/security-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Notifications',
            route: "/notification",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Connected Apps',
            route: "/connected-apps",
            hasSubRoute: false,
            showSubRoute: false,
          },
        ],
      },
      {
        title: 'Website Settings',
        hasSubRoute: true,
        showSubRoute: false,
        subRoutes: [
          {
            title: 'System Settings',
            route: "/system-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Company Settings',
            route: "/company-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Localization',
            route: "/localization-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Prefixes',
            route: "/prefixes",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Preference',
            route: "/preference",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Appearance',
            route: "/appearance",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Social Authentication',
            route: "/social-authentication",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Language',
            route: "/language-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
        ],
      },

      {
        title: 'App Settings',
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: 'users',
        subRoutes: [
          {
            title: 'Invoice',
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                title: 'Invoice Settings',
                route: "/invoice-settings",
                hasSubRoute: true,
                showSubRoute: true,
                subRoutes: [],
              },
              {
                title: 'Invoice Template',
                route: "/invoice-template",
                hasSubRoute: true,
                showSubRoute: true,
                subRoutes: [],
              },
            ],
          },
          {
            title: 'Printer',
            route: "/printer-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'POS',
            route: "/pos-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Custom Fields',
            route: "/custom-fields",
            hasSubRoute: false,
            showSubRoute: false,
          },
        ],
      },
      {
        title: 'System Settings',
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: 'users',
        subRoutes: [
          {
            title: 'Email',
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                title: 'Email Settings',
                route: "/email-settings",
                hasSubRoute: false,
                showSubRoute: false,
              },
              {
                title: 'Email Template',
                route: "/email-template",
                hasSubRoute: false,
                showSubRoute: false,
              },

            ],
          },
          {
            title: 'SMS',
            hasSubRoute: true,
            showSubRoute: true,
            subRoutes: [
              {
                title: 'SMS Settings',
                route: "/sms-settings",
                hasSubRoute: false,
                showSubRoute: false,
              },
              {
                title: 'SMS Template',
                route: "/sms-template",
                hasSubRoute: false,
                showSubRoute: false,
              },
            ]
          },
          {
            title: 'OTP',
            route: "/otp-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'GDPR Cookies',
            route: "/gdpr-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
        ],
      },
      {
        title: 'Financial Settings',
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: 'users',
        subRoutes: [
          {
            title: 'Payment Gateway',
            route: "/payment-gateway-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Bank Accounts',
            route: "/bank-settings-grid",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Tax Rates',
            route: "/tax-rates",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Currencies',
            route: "/currency-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
        ],
      },
      {
        title: 'Other Settings',
        hasSubRoute: true,
        showSubRoute: false,
        activeRoute: 'users',
        subRoutes: [
          {
            title: 'Storage',
            route: "/storage-settings",
            hasSubRoute: false,
            showSubRoute: false,
          },
          {
            title: 'Ban IP Address',
            route: "/ban-ip-address",
            hasSubRoute: false,
            showSubRoute: false,
          },
        ],
      },
      {
        title: 'Logout',
        hasSubRoute: false,
        showSubRoute: false,
        route: "/signin",
      },
      
    ],
  },
  {
    title: 'More',
    hasSubRoute: true,
    icon: 'circle-plus',
    showSubRoute: false,
    activeRoute: 'More',
    subRoutes: [

      {
        title: 'People',
        hasSubRoute: true,
        showSubRoute: false,
        //   route: routes.users,
        subRoutes: [
          {
            title: 'Customers',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/customers",
            subRoutes: [],
          },
          {
            title: 'Billers',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/billers",
            subRoutes: [],
          },
          {
            title: 'Suppliers',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/suppliers",
            subRoutes: [],
          },
          {
            title: 'Stores',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/store-list",
            subRoutes: [],
          },
          {
            title: 'Warehouses',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/warehouse",
            subRoutes: [],
          },
        ],
      },
      {
        title: 'User Management',
        hasSubRoute: true,
        showSubRoute: false,
        //   route: routes.users,
        subRoutes: [
          {
            title: 'Users',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/users",
            subRoutes: [],
          },
          {
            title: 'Roles & Permissions',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/roles-permissions",
            subRoutes: [],
          },
          {
            title: 'Delete Account Request',
            hasSubRoute: false,
            showSubRoute: false,
            route: "/delete-account",
            subRoutes: [],
          },
        ],
      },
     
      {
        title: 'Documentation',
        hasSubRoute: false,
        showSubRoute: false,
        activeRoute: 'users',
      },
      {
        title: 'Changelog v2.0.7',
        hasSubRoute: false,
        showSubRoute: false,
        activeRoute: 'users',
      },
    ],
  },

];
